# Production image, copy all the files and run next
FROM node:alpine AS runner
WORKDIR /app

#COPY package.json package-lock.json ./

COPY . /
RUN npm install

ENV NODE_ENV development

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
#COPY /app/public ./public
#COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
#COPY /app/node_modules ./node_modules
#COPY /app/package.json ./package.json

EXPOSE 3000

ENV PORT 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev"]