name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env: 
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
  API_SECRET: ${{ secrets.API_SECRET }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag suomiton/firehay-measurements-web:$(date +%s)
